### ISSUE TITLE
Slides are being processed, output is empty

### ISSUE THREAD

**Issue by hahamark1** [MaryamHaghighat/PathProfiler#4]
Hello,

I was trying to see the output performance of the segmentation and quality models on some example slides from TCGA. However, the output seems to be empty, both for the mask and the different outputs from the quality assessment module. 

I do not encounter any errors and run the models with the default settings. 

Do you have any ideas what could be the issue?

**Comment by MaryamHaghighat** [comment]
Hi Mark,

Are the pertained models (checkpoints) loaded properly?

**Comment by hahamark1** [comment]
In the output I see:
`=> loading checkpoint '/Users/markromme/Downloads/checkpoint_106.pth'
=> loaded checkpoint '/Users/markromme/Downloads/checkpoint_106.pth' (epoch 107)`

**Comment by MaryamHaghighat** [comment]
Empty output means you are not reading the images properly. Can you please check if your input to the model is not all zero?
